version: "3.4"

services:

  jikan-rest-api:
    build:
      context: jikan
      dockerfile: Dockerfile
    depends_on:
      - jikan-redis
    ports:
      - "9001:80"
    networks:
      - default
    restart: always
  scrapy:
    build:
      context: scrapy
      dockerfile: Dockerfile
    depends_on:
      - jikan-redis
      - jikan-rest-api
    network_mode: host
    restart: always
    volumes:
      - ./appdata:/appdata
    command: sh -c 'scrapy crawl user_interactions -o /appdata/user_interactions.csv -s JOBDIR=appdata/interactions_spider'
  jikan-redis:
    image: redis
    restart: always
